# Generated by Django 5.1 on 2024-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_accommodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='accommodation',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('accommodation_receptionist', 'Accommodation_Receptionist'), ('agency_receptionist', 'Agency_Receptionist'), ('client', 'Client')], max_length=50, null=True),
        ),
    ]
