# Generated by Django 5.1 on 2024-10-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_role_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('accommodation_receptionist', 'Accommodation_Receptionist'), ('agency_receptionist', 'Agency_Receptionist'), ('client', 'Client')], default='client', max_length=50, null=True),
        ),
    ]
