# Generated by Django 5.1 on 2024-10-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_reservation_full_name_travelplan_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.PositiveIntegerField(default='237652996622'),
        ),
    ]
